// /types/navigation.ts

import { NativeStackScreenProps } from '@react-navigation/native-stack';

export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  SignIn: undefined;
  SignUp: undefined;
  Home: undefined;
  EnterName: undefined;
  EnterContact: undefined;
  EnterEmail: undefined;
  EmailVerification: undefined;
  CreatePassword: undefined;
  SelectLocation: { type: 'from' | 'to' };
  SelectDate: undefined;
  SelectTime: undefined;
  SelectSeats: undefined;
  BookRide: undefined;
  AvailableRides: undefined;
  TripDetails: { driverId: string };
  TripGoldenRules: undefined;
  OtherPassengers: undefined;
  Profile: undefined;
  Payment: undefined;
  BookingConfirmed: undefined;
  LookingForRides: undefined;
  RideRating: undefined;
  LeaveComment: undefined;
  RideCompleted: undefined;
  BookingAccepted: undefined;
  DriverEnRoute: undefined;
  DriverArrived: undefined;
  InTripMap: undefined;
  TwoFactorAuth: undefined;
  Trips: undefined;
};

export type SplashScreenProps = NativeStackScreenProps<RootStackParamList, 'Splash'>;
export type WelcomeScreenProps = NativeStackScreenProps<RootStackParamList, 'Welcome'>;
export type SignInScreenProps = NativeStackScreenProps<RootStackParamList, 'SignIn'>;
export type SignUpScreenProps = NativeStackScreenProps<RootStackParamList, 'SignUp'>;
export type HomeScreenProps = NativeStackScreenProps<RootStackParamList, 'Home'>;
export type EnterNameScreenProps = NativeStackScreenProps<RootStackParamList, 'EnterName'>;
export type EnterContactScreenProps = NativeStackScreenProps<RootStackParamList, 'EnterContact'>;
export type EnterEmailScreenProps = NativeStackScreenProps<RootStackParamList, 'EnterEmail'>;
export type EmailVerificationScreenProps = NativeStackScreenProps<RootStackParamList, 'EmailVerification'>;
export type CreatePasswordScreenProps = NativeStackScreenProps<RootStackParamList, 'CreatePassword'>;
export type SelectLocationScreenProps = NativeStackScreenProps<RootStackParamList, 'SelectLocation'>;
export type SelectDateScreenProps = NativeStackScreenProps<RootStackParamList, 'SelectDate'>;
export type SelectTimeScreenProps = NativeStackScreenProps<RootStackParamList, 'SelectTime'>;
export type SelectSeatsScreenProps = NativeStackScreenProps<RootStackParamList, 'SelectSeats'>;
export type BookRideScreenProps = NativeStackScreenProps<RootStackParamList, 'BookRide'>;
export type AvailableRidesScreenProps = NativeStackScreenProps<RootStackParamList, 'AvailableRides'>;
export type TripDetailsScreenProps = NativeStackScreenProps<RootStackParamList, 'TripDetails'>;
export type TripGoldenRulesScreenProps = NativeStackScreenProps<RootStackParamList, 'TripGoldenRules'>;
export type OtherPassengersScreenProps = NativeStackScreenProps<RootStackParamList, 'OtherPassengers'>;
export type ProfileScreenProps = NativeStackScreenProps<RootStackParamList, 'Profile'>;
export type PaymentScreenProps = NativeStackScreenProps<RootStackParamList, 'Payment'>;
export type BookingConfirmedScreenProps = NativeStackScreenProps<RootStackParamList, 'BookingConfirmed'>;
export type LookingForRidesScreenProps = NativeStackScreenProps<RootStackParamList, 'LookingForRides'>;
export type RideRatingScreenProps = NativeStackScreenProps<RootStackParamList, 'RideRating'>;
export type LeaveCommentScreenProps = NativeStackScreenProps<RootStackParamList, 'LeaveComment'>;
export type RideCompletedScreenProps = NativeStackScreenProps<RootStackParamList, 'RideCompleted'>;
export type BookingAcceptedScreenProps = NativeStackScreenProps<RootStackParamList, 'BookingAccepted'>;
export type DriverEnRouteScreenProps = NativeStackScreenProps<RootStackParamList, 'DriverEnRoute'>;
export type DriverArrivedScreenProps = NativeStackScreenProps<RootStackParamList, 'DriverArrived'>;
export type InTripMapScreenProps = NativeStackScreenProps<RootStackParamList, 'InTripMap'>;
export type TwoFactorAuthScreenProps = NativeStackScreenProps<RootStackParamList, 'TwoFactorAuth'>;
export type TripsScreenProps = NativeStackScreenProps<RootStackParamList, 'Trips'>;

